# settings.py

# Screen dimensions
SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600

# Player settings
PLAYER_SPEED = 10
PLAYER_WIDTH = 50
PLAYER_HEIGHT = 50

# Bullet settings
BULLET_SPEED = 20
BULLET_WIDTH = 5
BULLET_HEIGHT = 10

# Enemy settings
ENEMY_SPEED = 2
ENEMY_WIDTH = 40
ENEMY_HEIGHT = 40

# Boss settings
BOSS_HEALTH_INITIAL = 20
BOSS_SHOOT_INTERVAL = 2000  # milliseconds

# Wave settings
INITIAL_ENEMY_COUNT = 3
ENEMY_COUNT_INCREASE_PER_WAVE = 2
